apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
        service-type: internal
    spec:
      containers:
      - name: logger
        image: ilvladik/logger:dev
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 5052
        
---
apiVersion: v1
kind: Service
metadata:
  name: logging-service
spec:
  selector:
    app: logging-service
  ports:
  - port: 5052
    targetPort: 5052