apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting-service
  template:
    metadata:
      labels:
        app: greeting-service
        service-type: internal
    spec:
      containers:
      - name: greeting-service
        image: ilvladik/greeting-service:dev
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5054

---
apiVersion: v1
kind: Service
metadata:
  name: greeting-service
spec:
  selector:
    app: greeting-service
  ports:
    - port: 5054
      targetPort: 5054